[build]
  publish = "build"

[[redirects]]
  from = "/"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/image"
  to = "/image.html"
  status = 200

[[redirects]]
  from = "/pdf"
  to = "/pdf.html"
  status = 200

[[redirects]]
  from = "/insound"
  to = "/insound/index.html"
  status = 200
